version: '3.9'

services:
    php-env:
        build: .
        volumes:
            - .:/var/www/html/
            - ./Containers/php.ini:/usr/local/etc/php/php.ini
        ports:
            - 9000:80
    mysql:
        image: mysql:latest
        container_name: mysql_con
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=test
          - MYSQL_PASSWORD=root
          - MYSQL_DATABASE=flights
        volumes:
          - my-db:/var/lib/mysql
          - ./Containers/dump.sql:/docker-entrypoint-initdb.d/mydump.sql
        ports:
          - '3306:3306'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart : always
        ports:
          - "8082:80"
        environment:
          - PMA_ARBITRARY=1

volumes:
    my-db: